version: '3'
services:
  rms-portal-dev:
    container_name: rms-portal-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
