version: '3'
services:
  rms-portal:
    container_name: rms-portal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:80
    environment:
      NODE_ENV: production

  rms-portal-dev:
    container_name: rms-portal
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
